(defun qsort (seq &optional (less-than #'<))
  "revive a classic bug: (qsort '(2 1 3)) ==> Recursive Error"
  (let ((len (length seq)))
    (if (< len 2)
        (copy-seq seq)
        (let ((mid-elem (elt seq (floor len 2))) ; BUG. correct: (floor len 2) -> (random len)
              (lessers  ())
              (greaters ()))
          (count () seq :key #'(lambda (x) (if (funcall less-than x mid-elem)
                                               (push x lessers)
                                               (push x greaters))))
          (concatenate 'list (qsort lessers) (qsort greaters))))))
